
game_settings:
  game_exe_path: "D:\\AI_Knight\\AI-Cure\\Game_depolyment\\HoloCure.exe"
  max_time_min: 120

training_settings:
  actions_per_second: 4
  max_steps: 5000
  #output_dir: None # will default to project output dir
  run_steps: 64
  runs_per_update: 3
  updates_per_checkpoint: 4
  learn_steps: 40

vision_settings:
  model_path: "D:\\AI_Knight\\AI-Cure\\screen_reader\\font_train\\trained_model\\v004\\hcure_font_model_4.traineddata"
  start_up_time: 15

inputs:
  move_left: "a"
  move_right: "d"
  move_down: "s"
  move_up: "w"
  proceed: "enter"
  #dexit: "esc"



