CONFIG_PATH = "E:\\Python\\Ai_Knight\\config.yaml"
CHEAT_ENGINE_TABLE_PATH = "E:\\Python\\Ai_Knight\\memory_reader\\table_report.CT"
HCURE_GAME_EXE = "E:\\holocure\\Game_depolyment\\HoloCure.exe"
HCURE_OCR_MODEL_PATH = "E:\\Python\\Ai_Knight\\screen_reader\\font_train\\trained_model\\hcure_font_model_5.traineddata"
IMAGE_MISC_TRAING_DIR = "E:\\Python\\Ai_Knight\\screen_reader\\font_train\\data_capture\\misc_training"
DEFAULT_BOX = "E:\\Python\\Ai_Knight\\screen_reader\\font_train\\data_capture\\hcure_level_up\\back-up\\default_box.box"
LEVEL_UP_IMAGES = "E:\\Python\\Ai_Knight\\screen_reader\\font_train\\data_capture\\hcure_level_up\\bad"
LEVEL_UP_OUT_PUT_DIR = "E:\\Python\\Ai_Knight\\screen_reader\\font_train\\data_capture\\hcure_level_up"